development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 360
  checkout_timeout: 720
  database: tshirts_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: tshirts_test
  username: root
  password:

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 360
  checkout_timeout: 720
  database: tshirts_staging
  username: tshirts
  password: C4iu3NcyGPX