---
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - camiseteria
  - chicorei
  - redbug
  - vandal
  - [default, 2]
development:
  :concurrency: 20
staging:
  :concurrency: 30
production:
  :concurrency: 60